"""Initial migration

Revision ID: 3568d150ffb2
Revises: 
Create Date: 2024-10-29 17:38:46.497994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3568d150ffb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personnel',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('company_name', sa.String(length=100), nullable=False),
    sa.Column('department_name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=False),
    sa.Column('rank', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.CheckConstraint('gender IN ("男", "女")', name='gender_check'),
    sa.PrimaryKeyConstraint('employee_id')
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('role_code', sa.String(length=10), nullable=False),
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('role_code'),
    sa.UniqueConstraint('role_id')
    )
    op.create_table('room',
    sa.Column('room_name', sa.String(length=100), nullable=False),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=100), nullable=False),
    sa.Column('room_type', sa.String(length=100), nullable=False),
    sa.Column('room_capacity', sa.Integer(), nullable=False),
    sa.Column('room_price', sa.Integer(), nullable=False),
    sa.Column('room_status', sa.String(length=100), nullable=False),
    sa.Column('room_image_path', sa.String(length=255), nullable=True),
    sa.CheckConstraint('room_status IN ("空闲", "使用中", "维修中", "报废")', name='room_status_check'),
    sa.PrimaryKeyConstraint('room_number'),
    sa.UniqueConstraint('room_number')
    )
    op.create_table('spare_parts',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('part_number', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('last_inspection_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.CheckConstraint('status IN ("可用", "待检", "维修中", "报废")', name='status_check'),
    sa.PrimaryKeyConstraint('part_number'),
    sa.UniqueConstraint('part_number')
    )
    op.create_table('checkins',
    sa.Column('checkin_id', sa.Integer(), nullable=False),
    sa.Column('occupant_name', sa.String(length=100), nullable=False),
    sa.Column('employee_id', sa.String(length=100), nullable=False),
    sa.Column('room_number', sa.String(length=100), nullable=False),
    sa.Column('reason', sa.String(length=100), nullable=False),
    sa.Column('checkin_date', sa.Date(), nullable=False),
    sa.Column('checkout_date', sa.Date(), nullable=True),
    sa.Column('is_historical', sa.Integer(), nullable=False),
    sa.CheckConstraint('reason IN ("因公", "因私")', name='reason_check'),
    sa.ForeignKeyConstraint(['employee_id'], ['personnel.employee_id'], ),
    sa.ForeignKeyConstraint(['room_number'], ['room.room_number'], ),
    sa.PrimaryKeyConstraint('checkin_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('role_code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['role_code'], ['role.role_code'], ),
    sa.PrimaryKeyConstraint('username'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('checkins')
    op.drop_table('spare_parts')
    op.drop_table('room')
    op.drop_table('role')
    op.drop_table('personnel')
    # ### end Alembic commands ###
